sudo: required
language: python
cache: pip
services:
  - docker
env:
  - ANSIBLE='ansible>=2.4.0,<2.5.0'
  - ANSIBLE='ansible>=2.5.0,<2.6.0'
matrix:
  fast_finish: true
install:
  - pip install ${ANSIBLE} 'ansible-lint>=3.4.15' 'molecule==1.25.0' docker git-semver 'testinfra>=1.7.0,<=1.10.1' jmespath
before_script:
  - ansible-lint tests/playbook.yml
script:
  - molecule test
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/releaser.sh
  on:
    branch: master
branches:
  only:
    - master
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
